// THE SKELETON MAY NOT HAND AN AUTHOR A LINE ITS OWN LOADER REFUSES.
//
// `harness init` writes a profile whose ladder block is half declaration and
// half invitation: some fields are declared live, and the rest are left as
// commented `<field>: []` lines under a sentence telling the author to fill them
// in — "The execution rungs stay unnamed until the steps exist. You said this
// project has them, so name them here when you write them:". An adopter who does
// the one thing that sentence asks must not be refused by the lane that wrote
// it. That is the invariant here, and it is not about any particular field.
//
// WHY IT IS A CLASS AND NOT A TYPO. The ladder has an ordering rule the loader
// enforces — a rung whose lower rung is undeclared is refused, not graded — and
// the seeded legend states that rule twenty lines above the invitation, in
// capitals ("DECLARE FROM THE BOTTOM UP"). Any code that chooses which fields to
// invite is therefore a SECOND place that has to know the ordering rule, and a
// second place always drifts from the first. The only durable defence is to stop
// reading the invitation and start executing it: take what the skeleton wrote,
// fill in what it asked for, and put the result through the resolver the lane
// uses. Then no future invitation can contradict the loader either.
//
// MEASURED, NOT REASONED. On 2026-09-11 the interview answered `s` (skip) to the
// first question and `1` to the second — a real, ordinary session — and returned
// `{l3Execution: "yes — the shippable artifact, ..."}`. The skeleton for that
// answer writes exactly one invitation, `// l3Execution: [],`, and filling it in
// is refused by evidence-ladder.mjs with "declares l3Execution without
// l2Execution — the shippable program cannot run where no program runs". The
// refusal is correct; the invitation is what is wrong.
//
// THE DOMAIN IS profileSkeleton's OWN. Its `answers` parameter is documented as
// "bare field name → the option string that field offers, verbatim", so every
// map over the contract's menu fields is in scope, whether or not today's
// interview can reach it. A skeleton is a pure function and this asks it the
// whole question.
import { test } from "node:test";
import assert from "node:assert/strict";

import { profileSkeleton } from "../packages/harness/install/init.mjs";
import { CONTRACT, MENU_FIELDS } from "../packages/harness/src/lib/profile-contract.mjs";
import { evidenceLadderFor } from "../packages/harness/src/lib/evidence-ladder.mjs";

/** Every ladder field the contract knows, so an invitation is recognised by name and never by a list kept here. */
const LADDER_FIELDS = Object.keys(CONTRACT.ladder.fields);

/** The menu fields, by the bare name the interview records and `answers` is keyed with. */
const MENU = MENU_FIELDS.filter((p) => p.startsWith("ladder.")).map((p) => p.slice("ladder.".length));

/** Every `answers` map over the menu: each field skipped, or answered with each option it offers. */
function everyAnswerMap() {
  let maps = [{}];
  for (const field of MENU) {
    const next = [];
    for (const base of maps) {
      next.push(base);
      for (const option of CONTRACT.ladder.fields[field].options) next.push({ ...base, [field]: option });
    }
    maps = next;
  }
  return maps;
}

/** The LIVE `export const ladder = {...}` block, or null when the skeleton seeded the commented one. */
function liveLadderSource(skeleton) {
  const start = skeleton.indexOf("\nexport const ladder = {");
  if (start === -1) return null;
  const end = skeleton.indexOf("\n};", start);
  assert.notEqual(end, -1, "a live ladder block was opened and never closed — the skeleton is not valid JavaScript");
  return skeleton.slice(start + 1, end + 3);
}

/**
 * The fields a block INVITES: named in a comment line as `<field>: []`, which is
 * the shape the skeleton writes for "name them here when you write them". Read
 * off the generated bytes, so a differently worded invitation of the same shape
 * is judged the same way.
 */
function invitedFields(block) {
  const invited = [];
  for (const line of block.split("\n")) {
    const comment = /^\s*\/\/\s?(.*)$/.exec(line);
    if (!comment) continue;
    for (const m of comment[1].matchAll(/([A-Za-z_$][\w$]*)\s*:\s*\[\s*\]/g)) {
      if (LADDER_FIELDS.includes(m[1]) && !invited.includes(m[1])) invited.push(m[1]);
    }
  }
  return invited;
}

test("every declaration the seeded profile invites an author to fill in is one the ladder resolver accepts", async () => {
  const refused = [];
  let liveBlocks = 0;
  let invitations = 0;

  for (const answers of everyAnswerMap()) {
    const skeleton = profileSkeleton("probe", { sourceRoots: ["src"], tiers: ["unit"], lang: "Python", answers });
    const block = liveLadderSource(skeleton);
    if (!block) continue;
    liveBlocks += 1;

    // Imported rather than pattern-matched: what the block DECLARES is whatever
    // JavaScript says it declares, and loading it also proves the generated
    // block parses at all.
    const { ladder: declared } = await import(`data:text/javascript,${encodeURIComponent(block)}`);
    const invited = invitedFields(block);
    invitations += invited.length;

    // The author does exactly what the comment asks: writes a step name where
    // the skeleton left room for one. One name is enough — the refusal under
    // test is about WHICH field is named, never how many.
    const filled = { ...declared };
    for (const field of invited) filled[field] = ["aStepThisProjectWillWrite"];

    const resolved = evidenceLadderFor({ id: "probe", ladder: filled }, null);
    if (!resolved.ok) refused.push({ answers, invited, declared, reason: resolved.reason });
  }

  // A lint that stopped finding live blocks or stopped finding invitations
  // inside them would pass in silence while asserting nothing at all.
  assert.ok(liveBlocks > 0, "no answer produced a live ladder block — this test no longer reaches the code it is for");
  assert.ok(invitations > 0, `found ${liveBlocks} live ladder blocks and not one invitation in them — this test is inert`);

  assert.deepEqual(
    refused.map((r) => `${JSON.stringify(r.answers)} → ${r.invited.join(", ")}`),
    [],
    refused
      .map(
        (r) =>
          `\n  Answered ${JSON.stringify(r.answers)}, the skeleton declares ${JSON.stringify(r.declared)} and invites\n` +
          `  the author to fill in ${r.invited.map((f) => `\`${f}\``).join(", ")}. Filling it in is refused:\n` +
          `    ${r.reason}`,
      )
      .join("\n") +
      "\n\n  The skeleton is the first and often only ladder documentation an adopter reads, and it is written by " +
      "the same product that refuses what it suggests. Invite only the fields the resolver would accept — the rungs " +
      "are climbed in order, so a higher rung's field cannot be offered alone — or say plainly in the comment that " +
      "the rung beneath it has to be declared too.",
  );
});
